import { palette } from '@/styles/palette';

export const Colors = {
    primary: palette.teal.main,
    pink: palette.sky.main,
    secondary: palette.green.main,
    darkBlue: palette.teal.dark,
    brandPurple: palette.teal.main,
    brandSalmon: palette.teal.light,
    glassSurface: 'rgba(255, 255, 255, 0.2)',
    glassBorder: 'rgba(255, 255, 255, 0.3)',
    yellow: palette.teal.main,
    statMagenta: palette.sky.accent,
    cream: palette.sky.main,
    onboardingNavy: palette.teal.dark,
    onboardingNavyLight: palette.teal.main,
    onboardingSalmon: palette.teal.light,
    onboardingGlass: palette.teal.gridOverlay,
    onboardingGlassBorder: 'rgba(255, 255, 255, 0.2)',
    onboardingDotInactive: 'rgba(255, 255, 255, 0.35)',
    tabPrimary: palette.neutral.white,
    tabSecondary: palette.neutral.white,
    tabActive: palette.teal.main,
    tabInactive: palette.neutral.textMuted,
    success: palette.green.main,
    error: palette.status.error,
    warning: palette.status.warning,
    info: palette.status.info,
    black: palette.neutral.black,
    white: palette.neutral.white,
    gray50: palette.neutral.gray50,
    gray100: palette.neutral.gray100,
    gray200: palette.neutral.gray200,
    gray300: palette.neutral.gray300,
    gray400: palette.neutral.gray400,
    gray500: palette.neutral.gray500,
    gray600: '#334155',
    gray700: palette.neutral.text,
    background: palette.neutral.background,
    surface: palette.neutral.white,
    text: palette.neutral.text,
    textSecondary: palette.neutral.textSecondary,
    inputBackground: palette.neutral.white,
    inputBorder: palette.neutral.border,
    inputPlaceholder: palette.neutral.textMuted,
    inputText: palette.neutral.text,
    statusBar: 'dark-content' as const,
    inputBackgroundApp: palette.neutral.gray50,
    buttonBorder: palette.teal.dark,
    buttonDisabled: palette.neutral.gray200,
    buttonSplitFillStart: palette.teal.light,
    buttonSplitFillMid: palette.teal.main,
    buttonSplitFillEnd: palette.teal.dark,
    buttonSplitBorderGradient: ['#FFFFFF', palette.teal.main, palette.teal.dark] as readonly [string, string, string],
    buttonSplitLabel: palette.neutral.white,
    buttonSplitDivider: palette.neutral.white,
    buttonSplitIconBackground: palette.teal.dark,
    buttonSplitIconStroke: palette.neutral.white,
    gradientPrimary: [palette.sky.main, palette.neutral.white] as readonly [string, string],
    gradientButtonPrimary: [palette.teal.main, palette.teal.dark] as readonly [string, string],
    gradientSecondary: [palette.teal.dark, palette.teal.main, palette.teal.dark] as readonly [string, string, string],
    gradientNew: ['rgba(0, 0, 0, 0.01)', 'rgba(0, 0, 0, 0.8)'] as readonly [string, string],
    gradientFooter: [palette.teal.dark, palette.teal.main] as readonly [string, string],
    iconPrimary: palette.neutral.gray500,
    iconSecondary: palette.neutral.textMuted,
    shimmerChildProfile: [palette.sky.main, palette.teal.surface, palette.sky.main] as readonly [string, string, string],
    shimmerOnWhite: ['#F2F2F2', '#E0E0E0', '#F2F2F2'] as readonly [string, string, string],
    blackOpacity60: 'rgba(0, 0, 0, 0.6)',
    whiteOpacity60: 'rgba(255, 255, 255, 0.6)',
    transparent: 'transparent',
    orange: palette.status.pending,
    supportEmail: palette.status.error,
    actionIconBlue: palette.sky.accent,
    actionIconOrange: palette.status.pending,
    actionIconRed: palette.status.error,
    actionIconGrey: palette.neutral.gray500,
    sessionBannerBg: '#FFE3E3',
    sessionBannerText: palette.status.error,
    sessionDetailIconBg: palette.teal.main,
    insuranceBronze: [palette.teal.dark, palette.teal.main] as readonly [string, string],
    insuranceSilver: [palette.neutral.gray400, palette.neutral.gray300] as readonly [string, string],
    insuranceGold: [palette.green.dark, palette.green.light] as readonly [string, string],
    insurancePlatinum: [palette.sky.accent, palette.sky.border] as readonly [string, string],
} as const;

export type AppColors = typeof Colors;
export const commonColors = Colors;
