import { palette } from '@/styles/palette';

/** Flat color API — clinic light tokens only. */
export const Colors = {
    primary: palette.lime.main,
    accentBlue: palette.lime.main,
    pink: palette.lime.highlight,
    secondary: palette.medical.success,
    darkBlue: palette.lime.dark,
    brandPurple: palette.lime.main,
    brandSalmon: palette.olive.light,
    glassSurface: palette.lime.surface,
    glassBorder: palette.onCard.border,
    yellow: palette.lime.main,
    statMagenta: palette.medical.stat,
    cream: palette.cream,
    ink: palette.ink,
    onboardingNavy: palette.lime.dark,
    onboardingNavyLight: palette.lime.main,
    onboardingSalmon: palette.olive.light,
    onboardingGlass: palette.olive.gridOverlay,
    onboardingGlassBorder: palette.onCard.border,
    onboardingDotInactive: palette.olive.muted,
    tabPrimary: palette.olive.card,
    tabSecondary: palette.olive.card,
    tabActive: palette.lime.main,
    tabInactive: palette.olive.muted,
    success: palette.medical.success,
    error: palette.medical.error,
    warning: palette.medical.warning,
    info: palette.medical.info,
    emergency: palette.medical.emergency,
    black: palette.neutral.black,
    white: palette.neutral.white,
    gray50: palette.olive.deeper,
    gray100: palette.olive.main,
    gray200: palette.olive.main,
    gray300: palette.olive.muted,
    gray400: palette.onCard.textSecondary,
    gray500: palette.onCard.icon,
    gray600: palette.onCard.textMuted,
    gray700: palette.cream,
    background: palette.olive.dark,
    surface: palette.olive.card,
    screen: palette.olive.dark,
    text: palette.cream,
    textSecondary: palette.onCard.textSecondary,
    textMuted: palette.onCard.textMuted,
    inputBackground: palette.olive.deeper,
    inputBorder: palette.onCard.border,
    inputPlaceholder: palette.onCard.textMuted,
    inputText: palette.cream,
    statusBar: 'dark-content' as const,
    inputBackgroundApp: palette.olive.deeper,
    buttonBorder: palette.lime.dark,
    buttonDisabled: palette.olive.main,
    buttonDisabledText: palette.olive.muted,
    buttonSplitFillStart: palette.lime.highlight,
    buttonSplitFillMid: palette.lime.main,
    buttonSplitFillEnd: palette.lime.dark,
    buttonSplitBorderGradient: [palette.lime.highlight, palette.lime.main, palette.lime.dark] as readonly [
        string,
        string,
        string,
    ],
    buttonSplitLabel: palette.ink,
    buttonSplitDivider: palette.ink,
    buttonSplitIconBackground: palette.lime.dark,
    buttonSplitIconStroke: palette.ink,
    gradientPrimary: [palette.olive.deeper, palette.olive.dark] as readonly [string, string],
    gradientButtonPrimary: [palette.lime.highlight, palette.lime.main, palette.lime.dark] as readonly [
        string,
        string,
        string,
    ],
    gradientSecondary: [palette.lime.dark, palette.lime.main, palette.lime.dark] as readonly [string, string, string],
    gradientNew: [palette.olive.deeper, palette.olive.dark] as readonly [string, string],
    gradientFooter: [palette.olive.deeper, palette.olive.main] as readonly [string, string],
    iconPrimary: palette.onCard.icon,
    iconSecondary: palette.onCard.textMuted,
    shimmerChildProfile: ['#E8F1FC', '#D5E6FA', '#E8F1FC'] as readonly [string, string, string],
    shimmerOnWhite: ['#F4F7FB', '#E8EEF5', '#F4F7FB'] as readonly [string, string, string],
    blackOpacity60: 'rgba(26, 29, 38, 0.6)',
    whiteOpacity60: 'rgba(255, 255, 255, 0.6)',
    transparent: 'transparent',
    orange: palette.medical.warning,
    supportEmail: palette.medical.error,
    actionIconBlue: palette.lime.main,
    actionIconOrange: palette.medical.warning,
    actionIconRed: palette.medical.emergency,
    actionIconGrey: palette.onCard.icon,
    sessionBannerBg: 'rgba(232, 93, 76, 0.12)',
    sessionBannerText: palette.medical.error,
    sessionDetailIconBg: palette.lime.main,
    insuranceBronze: [palette.lime.dark, palette.lime.main] as readonly [string, string],
    insuranceSilver: [palette.olive.main, palette.olive.muted] as readonly [string, string],
    insuranceGold: [palette.medical.successDark, palette.medical.success] as readonly [string, string],
    insurancePlatinum: [palette.lime.main, palette.olive.light] as readonly [string, string],
    onCard: palette.onCard,
    olive: palette.olive,
    lime: palette.lime,
    medical: palette.medical,
} as const;

export type AppColors = typeof Colors;
export const commonColors = Colors;
